/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Lakhan.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Lakhan-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1, 0]} scale={[4, 0.19, 9]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.005']} position={[-2, 1.1, 7.02]} scale={[1, 0.19, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.003']} position={[-4.25, 0.89, 6.25]} scale={[0.45, 0.27, 0.42]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[-4.25, 0.89, -6.41]} scale={[0.45, 0.27, 0.42]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[-6.19, 4.45, 0.16]} rotation={[0, 0, 2]} scale={[3.94, 0.07, 8.89]} />
      <mesh geometry={nodes.Aquote.geometry} material={materials.Aquote} position={[-6.18, 4.78, 0.05]} rotation={[Math.PI / 2, 0.43, -Math.PI / 2]} scale={[7.69, 1, 6.72]} />
      <mesh geometry={nodes.a.geometry} material={materials.a} position={[-1.98, 1.37, 4.21]} rotation={[-1.57, 1.57, 1.57]} scale={[1.8, 1.95, 1.56]} />
      <mesh geometry={nodes.a001.geometry} material={materials.a} position={[-1.98, 1.37, -4.18]} rotation={[-1.57, 1.57, 1.57]} scale={[1.8, 1.95, 1.56]} />
      <mesh geometry={nodes.L.geometry} material={materials.L} position={[-2.02, 1.36, 7]} rotation={[0, Math.PI / 2, 0]} scale={[1.85, 1.92, 1.52]} />
      <mesh geometry={nodes.K.geometry} material={materials.K} position={[-1.97, 1.31, 1.41]} rotation={[0, Math.PI / 2, 0]} scale={[1.87, 1.88, 1.54]} />
      <mesh geometry={nodes.H.geometry} material={materials.H} position={[-2.01, 1.34, -1.37]} rotation={[0, Math.PI / 2, 0]} scale={[1.88, 1.85, 1.55]} />
      <mesh geometry={nodes.N.geometry} material={materials.N} position={[-1.98, 1.38, -6.98]} rotation={[0, Math.PI / 2, 0]} scale={[1.8, 1.8, 1.5]} />
    </group>
  )
}

useGLTF.preload('/Lakhan-transformed.glb')
