/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Lakhan.gltf --transform
*/


import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Lakhan-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.24, 0.86, -5.48]} scale={[0.01, 0.002, 0.02]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube011_4.geometry} material={materials.Aquote} />
        <mesh geometry={nodes.Cube011_5.geometry} material={materials.a} />
        <mesh geometry={nodes.Cube011_6.geometry} material={materials.L} />
        <mesh geometry={nodes.Cube011_7.geometry} material={materials.K} />
        <mesh geometry={nodes.Cube011_8.geometry} material={materials.H} />
        <mesh geometry={nodes.Cube011_9.geometry} material={materials.N} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lakhan-transformed.glb')
