/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laptop1.gltf --transform
Author: gozdemrl (https://sketchfab.com/gozdemrl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ordinary-behavior-laptop-05ad8ea622744bd69aeefacb41ea466c
Title: Ordinary Behavior | Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>

          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Koltuk} position={[22.38, 116.06, 27.16]} rotation={[-Math.PI / 2, 0, 2.57]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Hali} position={[0, 111.24, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Firca} position={[-39.05, 127.76, 15.29]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Tuval} position={[-4.25, 128.52, 15.22]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Desk} position={[-37.59, 118.71, 27.03]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Boya_Kutusu} position={[-5.43, 123.4, 5.12]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Sandalye} position={[18.93, 121.68, -19.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.sovale} position={[0.76, 138.16, -16.47]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.zemin1} position={[0, 110.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
         
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/laptop1-transformed.glb')
