/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 test.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/test-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.25, 0.89, -6.41]} scale={[0.45, 0.27, 0.42]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials.Aquote} />
        <mesh geometry={nodes.Cube004_4.geometry} material={materials.H} />
        <mesh geometry={nodes.Cube004_5.geometry} material={materials.a} />
        <mesh geometry={nodes.Cube004_6.geometry} material={materials.N} />
        <mesh geometry={nodes.Cube004_7.geometry} material={materials.K} />
        <mesh geometry={nodes.Cube004_8.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube004_9.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube004_10.geometry} material={materials.L} />
      </group>
    </group>
  )
}

useGLTF.preload('/test-transformed.glb')
